# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:{
  "excludedUrls": "https://specifications.freedesktop.org/basedir-spec/latest/index.html",
  "linkHintCharacters": "asdfjklqwerzxc",
  "detectByCursorStyle": false,
  "scrollSize": 150,
  "openTabUrl": "hecho "# OPEN" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:IAM-ARN/OPEN.git
git push -u origin main
…or push an existing repository from the command line
git remote add origin git@github.com:IAM-ARN/OPEN.git
git branch -M main
git push -u origin main",
  "modifier"vimonline development",
  "smoothScroll": true,
  "scrollDuration": 25,
  "transparentBindings": true,
  "bindings": {https://neovim.io}
      "hintToggle": "f",
      "newTabHintToggle": "shift+f",
      "scrollUp": "k",
      "scrollDown": "j",
      "scrollLeft": "h",
      "scrollRight": "l",
      "scrollUpHalfPage": "u",
      "scrollDownHalfPage": "d",
      "goToPageTop": "g g",
      "goToPageBottom": "shift+g",
      "goToFirstInput": "g i",
      "goBack": "shift+h",
      "goForward": "shift+l",
      "reload": "r",
      "tabForward": "w",
      "tabBack": "q",
      "closeTab": "x",
      "openTab": "t"
https://desktop.docker.com/extensions/docker_labs-k8s-toolkit-extension/docker-extension-screenshots_s3_amazonaws_com/labs-k8s-toolkit/demo-k8s.gif  }
}

  push:{
  "excludedUrls": "https://specifications.freedesktop.org/basedir-spec/latest/index.html",
  "linkHintCharacters": "asdfjklqwerzxc",
  "detectByCursorStyle": false,
  "scrollSize": 150,
  "openTabUrl": "hecho "# OPEN" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:IAM-ARN/OPEN.git
git push -u origin main
…or push an existing repository from the command line
git remote add origin git@github.com:IAM-ARN/OPEN.git
git branch -M main
git push -u origin main",
  "modifier"vimonline development",
  "smoothScroll": true,
  "scrollDuration": 25,
  "transparentBindings": true,
  "bindings": {https://neovim.io}
      "hintToggle": "f",
      "newTabHintToggle": "shift+f",
      "scrollUp": "k",
      "scrollDown": "j",
      "scrollLeft": "h",
      "scrollRight": "l",
      "scrollUpHalfPage": "u",
      "scrollDownHalfPage": "d",
      "goToPageTop": "g g",
      "goToPageBottom": "shift+g",
      "goToFirstInput": "g i",
      "goBack": "shift+h",
      "goForward": "shift+l",
      "reload": "r",
      "tabForward": "w",
      "tabBack": "q",
      "closeTab": "x",
      "openTab": "t"
https://desktop.docker.com/extensions/docker_labs-k8s-toolkit-extension/docker-extension-screenshots_s3_amazonaws_com/labs-k8s-toolkit/demo-k8s.gif  }
}

    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      run: |
        mkdir -p data
        touch data/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
      run: vendor/bin/phpunit
